### ISSUE TITLE
Verizon email processor fails 

### ISSUE THREAD

**Issue by jasonyates** [networktocode/circuit-maintenance-parser#194]
### Environment

- Python version: 3.10.9
- circuit_maintenance_parser version: 2.2.0

### Expected Behavior

Verizon maintenance notification is parsed correctly

### Observed Behavior

Email parsing fails with error

```
Provider processing failed: Failed creating Maintenance notification for Verizon.
Details:
- Processor CombinedProcessor from Verizon failed due to: 'NoneType' object has no attribute 'find_all'

```

### Steps to Reproduce

1. circuit-maintenance-parser --data-file verizon.eml --data-type email --provider-type verizon

**Comment by chadell** [comment]
@jasonyates it would be great to get a sample (anonymized) that originates this issue to reproduce it

**Comment by jasonyates** [comment]
I submitted PR #196 that fixes this. The issue was the maintenance notifications I receive from VZ don't have <tbody> in the table containing the list of circuits, the parser was looking for <tbody> and then erroring.

I also added a new test containing an example of my notifications.
