### ISSUE TITLE
Equinix email processor fails

### ISSUE THREAD

**Issue by jasonyates** [networktocode/circuit-maintenance-parser#195]
### Environment

- Python version: 3.10.9
- circuit_maintenance_parser version: 2.2.0

### Expected Behavior

Equinix maintenance notification is parsed correctly

### Observed Behavior
Email parsing fails with error
```
Provider processing failed: Failed creating Maintenance notification for Equinix.
Details:
- Processor CombinedProcessor from Equinix failed due to: too many values to unpack (expected 3)
```

### Steps to Reproduce

1. circuit-maintenance-parser --data-file equinix.eml --data-type email --provider-type equinix

**Comment by chadell** [comment]
@jasonyates it would be great to get a sample (anonymized) that originates this issue to reproduce it

**Comment by jasonyates** [comment]
I submitted #197 to fix this. My notifications were failing for 2 reasons

1. A new impact statement from Equinix
2. Additional columns in the circuits table. IBX name was included in some notifications for EC product. Equinix Fabric product contains 14 columns in the notification to cover seller and subscriber details.
