### ISSUE TITLE
Upgrade to Pydantic 2.0

### ISSUE THREAD

**Issue by chadell** [networktocode/circuit-maintenance-parser#242]
### Environment

- circuit_maintenance_parser version: 

### Proposed Functionality

Use new Pydantic 2.0

**Comment by parameterEstimation** [comment]
Any update on this request? We are experiencing conflicts with `extendable-pydantic 1.1.1` which requires `pydantic 2.0.2`.

**Comment by chadell** [comment]
I'm currently working on it
