### ISSUE TITLE
Modern versions of `pydantic` don't provide `dotenv` extra, and it may not be needed anyways

### ISSUE THREAD

**Issue by glennmatthews** [networktocode/circuit-maintenance-parser#293]
### Environment

- Python version: 3.11
- circuit_maintenance_parser version: 2.6.1

```
pip install circuit_maintenance_parser
...
Collecting pydantic[dotenv]<3,>=1.10.4
  Downloading pydantic-2.8.2-py3-none-any.whl (423 kB)
...
WARNING: pydantic 2.8.2 does not provide the extra 'dotenv'
```

Still installs successfully in any case, but as far as I can tell we don't use pydantic's env-file feature anyways?

**Comment by chadell** [comment]
you are right, we are not using it, so it will be better to remove it
