### ISSUE TITLE
Dependencies are outdated

### ISSUE THREAD

**Issue by nniehoff** [networktocode/circuit-maintenance-parser#35]
### Environment

- Python version: 3.7.9
- circuit_maintenance_parser version: 1.2.1

I'm starting to run into dependency hell with some plugins.  There are some dependencies in this project (mainly click) which are outdated.  Also development dependencies should probably be set to * as to not cause issues down the line but they are development dependencies

### Expected Behavior

Plays nice in the sandbox with plugins dependent on newer versions of dependencies

### Observed Behavior

this plugin is dependent on click 7

**Comment by nniehoff** [comment]
We can enable renovate to point at this repo and open PRs as these come up if you would like.

**Comment by chadell** [comment]
> We can enable renovate to point at this repo and open PRs as these come up if you would like.

I like the idea, so we solve one for all.

**Comment by chadell** [comment]
Fixed in #36
