### ISSUE TITLE
Be able to handle gracefully notifications that do not contain any notification info

### ISSUE THREAD

**Issue by chadell** [networktocode/circuit-maintenance-parser#82]
### Environment

- circuit_maintenance_parser version: 2.0.1

### Proposed Functionality

Today, a `Provider` processing a notification can only return either the maintenance objects or raise a `ProviderError` when it was not possible to get, at least, a maintenance object from the notification.
Some times the notification parsed is not actually containing any relevant information and it's not actually needed to be parsed and raise an error, just signal that it was not containing any relevant info.

### Use Case

Being able to differentiate between parsing errors and non relevant notification would make the library clients able to handle each one in a different way.

**Comment by glennmatthews** [comment]
An example of the need for this is with Lumen, where emails regarding support tickets come from the same address (`no-reply@lumen.com`) as emails regarding scheduled maintenance. This results in a lot of "failed" parsing for the support ticket emails.

**Comment by chadell** [comment]
Fixed in #91
